Add new converters
FerrisChat/ferriswheel pull request #21
Opened 2021-12-15 02:21 UTC by DistortedPumpkin

Add new command argument converters: `MemberConverter`, `MessageConverter`, `RoleConverter`, `InviteConverter`

2021-12-15 02:23 UTC, DistortedPumpkin commented
Going to fix and re-create

2021-12-15 02:36 UTC, Cryptex-github commented
No that now how u do the return type I did it wrong before !

2021-12-15 02:37 UTC, Cryptex-github commented
You do it like Converter[Type]
class SomeConverter(Converter[SomeType])

2021-12-15 02:38 UTC, DistortedPumpkin commented
> You do it like Converter[Type] class SomeConverter(Converter[SomeType])

Oh alright, ill edit mine and the previously existing ones now

2021-12-15 04:14 UTC, Cryptex-github requested changes

2021-12-15 04:14 UTC, Cryptex-github commented on ferris/plugins/commands/converters.py
> +import re
Sort imports please

2021-12-15 04:42 UTC, Cryptex-github requested changes

2021-12-15 04:42 UTC, Cryptex-github commented on ferris/plugins/commands/converters.py
> -from ferris.errors import NotFound
And you need `from __future__ import `annotation` in order to use if `TYPE_CHECKING` guard

2021-12-17 04:16 UTC, Cryptex-github approved these changes

2021-12-17 04:18 UTC, merged